### PR TITLE
EldenBash Fixes

### PR DESCRIPTION
**Pull request by ghost**
I changed bin/bash to bin/sh because for those who use dash as the symlink to /bin/sh

and i added more game accurate changes like enemy fallen, and YOU DIED.

### CODE REVIEW

**Comment by tpglitch** [comment]
XD I abandond this account  a while ago I dont remember the pass but I will try to get it merged.

**Comment by ghost** [comment]
Haha, no worries.

**Comment by tpglitch** [comment]
Nah you better open this PR back up lol I will find that password

**Comment by ghost** [comment]
oh my bad lol

**Comment by tpglitch** [comment]
lol its just taking a little while longer cause i've been busy

**Comment by ghost** [comment]
yo its been 2 months you wanna close the req?

**Comment by tpglitch** [comment]
nah

**Comment by tpglitch** [comment]
i will find something my pass eventually

**Comment by tpglitch** [comment]
bro reopen it

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
dude, you got yo pass?

**Comment by tpglitch** [comment]
nah but i will soon i swear xD

**Comment by devepation** [comment]
Bout goddamn time

**Comment by ghost** [comment]
we can finally close?

**Comment by tpglitch** [comment]
It is merged?

**Pull request merged**
